
version: 2

models:
  - name: hosts_airbnb_paris
    description: "table in dbt_project_final database"
    columns:
      - name: host_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: listings_airbnb_paris
    description: "table in dbt_project_final database"
    columns:
      - name: host_id
        description: "hosts identification"
        tests:
          - unique
          - not_null
          

sources:
  - name: airbnb_paris
    database: dbt_project_final
    schema: public  
    tables:
      - name: hosts_airbnb_paris
      - name: listings_airbnb_paris


version: 2

exposures:

  - name: airbnb_paris
    label: Airbnb Paris
    type: dashboard
    maturity: high

    

    depends_on:
      - ref('activity')
      - ref('Listings_per_Host')
      - ref('licenses')
      - ref('short-term_rentals')
      - ref('Top_Hosts')
      - ref('room_type')
      - source("airbnb_paris","listings_airbnb_paris")
      - source("airbnb_paris","hosts_airbnb_paris")

    owner:
      name: Team Aliou Seydi, Fatimatou Ogo Seck, Henock Mackumbu Mboko et Sokhna Amainata Sy Diouf
      email: samsydiouf14@gmail.com